language: php
php:
  - hhvm

matrix:
    include:
        - php: "hhvm"
          env:
            - NO_COVERAGE=1
            - BZION_HHVM=1
    fast_finish: true

install:
 - curl -sS https://getcomposer.org/installer | php

before_script: bash -xe tests/initialize.sh

script: tests/runTests.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false

cache:
  directories:
  - vendor

notifications:
  webhooks:
    - http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always
