index:
    pattern:  /
    defaults: { _controller: 'Page', _action: 'showDefault' }

ban_list:
    pattern:    /bans
    defaults: { _controller: 'Ban', _action: 'list' }

login:
    pattern:    /login
    defaults: { _controller: 'Login', _action: 'login' }

logout:
    pattern:    /logout
    defaults: { _controller: 'Login', _action: 'logout' }

match_list:
    pattern:    /matches
    defaults: { _controller: 'Match', _action: 'list' }

match_by_team_list:
    pattern:    /matches/{team}
    defaults: { _controller: 'Match', _action: 'listByTeam' }

message_list:
    pattern:    /messages
    defaults: { _controller: 'Message', _action: 'compose' }

message_show_discussion:
    pattern:    /messages/{discussion}
    defaults: { _controller: 'Message', _action: 'show' }

news_list:
    pattern:    /news
    defaults: { _controller: 'News', _action: 'list' }

player_list:
    pattern:    /players
    defaults: { _controller: 'Player', _action: 'list' }

player_show:
    pattern:    /players/{player}
    defaults: { _controller: 'Player', _action: 'show' }

profile_show:
    pattern:    /profile
    defaults: { _controller: 'Profile', _action: 'show' }

profile_edit:
    pattern:    /profile/edit
    defaults: { _controller: 'Profile', _action: 'edit' }

server_list:
    pattern:    /servers
    defaults: { _controller: 'Server', _action: 'list' }

team_list:
    pattern:    /teams
    defaults: { _controller: 'Team', _action: 'list' }

team_show:
    pattern:    /teams/{team}
    defaults: { _controller: 'Team', _action: 'show' }

custom_page:
    pattern:    /{page}
    defaults: { _controller: 'Page', _action: 'show' }
