index:
    pattern:  /
    defaults: { _controller: 'Home', _action: 'show' }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    defaults: { _defaultHandler: true }

test_login:
    pattern:    /login/{user}
    defaults: { _controller: 'Login', _action: 'loginAsTestUser' }

admin_list:
    pattern:    /admins
    defaults: { _controller: 'Admin', _action: 'list' }

admin_wipe:
    pattern:    /admin/deleted
    defaults: { _controller: 'Admin', _action: 'wipe' }

api_leagueoverseer:
    pattern:    /api/leagueOverseer
    defaults: { _controller: 'LeagueOverseerHook', _action: 'query' }

ban_list:
    pattern:    /bans
    defaults: { _controller: 'Ban', _action: 'list' }

ban_create:
    pattern:    /bans/new
    defaults: { _controller: 'Ban', _action: 'create' }

ban_show:
    pattern:    /bans/{ban}
    defaults: { _controller: 'Ban', _action: 'show' }

ban_edit:
    pattern:    /bans/{ban}/edit
    defaults: { _controller: 'Ban', _action: 'edit' }

ban_expire:
    pattern:    /bans/{ban}/unban
    defaults: { _controller: 'Ban', _action: 'unban' }

ban_delete:
    pattern:    /bans/{ban}/delete
    defaults: { _controller: 'Ban', _action: 'delete' }

invitation_accept:
    pattern:    /invitations/{invitation}
    defaults: { _controller: 'Invitation', _action: 'accept' }

login:
    pattern:    /login
    defaults: { _controller: 'Login', _action: 'login' }

logout:
    pattern:    /logout
    defaults: { _controller: 'Login', _action: 'logout' }

match_list:
    pattern:    /matches
    defaults: { _controller: 'Match', _action: 'list' }

match_by_team_list:
    pattern:    /teams/{team}/matches
    defaults: { _controller: 'Match', _action: 'list' }

match_by_team_list_sort:
    pattern:    /teams/{team}/matches/{type}
    defaults: { _controller: 'Match', _action: 'list' }

match_enter:
    pattern:    /matches/enter
    defaults: { _controller: 'Match', _action: 'create' }

match_delete:
    pattern:    /matches/{match}/delete
    defaults: { _controller: 'Match', _action: 'delete' }

message_list:
    pattern:    /messages
    defaults: { _controller: 'Message', _action: 'compose' }

message_discussion_show:
    pattern:    /messages/{discussion}
    defaults: { _controller: 'Message', _action: 'show' }

message_discussion_leave:
    pattern:    /messages/{discussion}/leave
    defaults: { _controller: 'Message', _action: 'leave' }

message_discussion_kick:
    pattern:    /messages/{discussion}/kick/{player}
    defaults: { _controller: 'Message', _action: 'kick' }

news_list:
    pattern:    /news
    defaults: { _controller: 'News', _action: 'list' }

news_new:
    pattern:    /news/new
    defaults: { _controller: 'News', _action: 'create' }

news_show:
    pattern:    /news/{article}
    defaults: { _controller: 'News', _action: 'show' }

news_edit:
    pattern:    /news/{article}/edit
    defaults: { _controller: 'News', _action: 'edit' }

news_delete:
    pattern:    /news/{article}/delete
    defaults: { _controller: 'News', _action: 'delete' }

news_category_show:
    pattern:    /news/category/{category}
    defaults: { _controller: 'News', _action: 'list' }

notification_list:
    pattern:    /notifications
    defaults: { _controller: 'Notification', _action: 'list' }

player_list:
    pattern:    /players
    defaults: { _controller: 'Player', _action: 'list' }

player_show:
    pattern:    /players/{player}
    defaults: { _controller: 'Player', _action: 'show' }

profile_show:
    pattern:    /profile
    defaults: { _controller: 'Profile', _action: 'show' }

profile_edit:
    pattern:    /profile/edit
    defaults: { _controller: 'Profile', _action: 'edit' }

profile_confirm:
    pattern:    /profile/confirm/{token}
    defaults: { _controller: 'Profile', _action: 'confirm' }

server_list:
    pattern:    /servers
    defaults: { _controller: 'Server', _action: 'list' }

server_new:
    pattern:    /servers/new
    defaults: { _controller: 'Server', _action: 'create' }

server_show:
    pattern:    /servers/{server}
    defaults: { _controller: 'Server', _action: 'show' }

server_delete:
    pattern:    /servers/{server}/delete
    defaults: { _controller: 'Server', _action: 'delete' }

server_edit:
    pattern:    /servers/{server}/edit
    defaults: { _controller: 'Server', _action: 'edit' }

team_list:
    pattern:    /teams
    defaults: { _controller: 'Team', _action: 'list' }

team_new:
    pattern:    /teams/new
    defaults: { _controller: 'Team', _action: 'create' }

team_show:
    pattern:    /teams/{team}
    defaults: { _controller: 'Team', _action: 'show' }

team_members:
    pattern:    /teams/{team}/members
    defaults: { _controller: 'Player', _action: 'list' }

team_join:
    pattern:    /teams/{team}/join
    defaults: { _controller: 'Team', _action: 'join' }

team_edit:
    pattern:    /teams/{team}/edit
    defaults: { _controller: 'Team', _action: 'edit' }

team_delete:
    pattern:    /teams/{team}/delete
    defaults: { _controller: 'Team', _action: 'delete' }

team_kick:
    pattern:    /teams/{team}/kick/{player}
    defaults: { _controller: 'Team', _action: 'kick' }

team_invite:
    pattern:    /teams/{team}/invite/{player}
    defaults: { _controller: 'Invitation', _action: 'invite' }

team_assign_leader:
    pattern:    /teams/{team}/change-leader/{player}
    defaults: { _controller: 'Team', _action: 'assignLeader' }

team_abandon:
    pattern:    /teams/{team}/abandon
    defaults: { _controller: 'Team', _action: 'abandon' }

custom_page_create:
    pattern:    /pages/new
    defaults: { _controller: 'Page', _action: 'create' }

custom_page:
    pattern:    /{page}
    defaults: { _controller: 'Page', _action: 'show' }

custom_page_edit:
    pattern:    /{page}/edit
    defaults: { _controller: 'Page', _action: 'edit' }

custom_page_delete:
    pattern:    /{page}/delete
    defaults: { _controller: 'Page', _action: 'delete' }

trailing_slash:
    path: /{url}
    defaults: { _controller: 'Redirecting', _action: 'removeTrailingSlash' }
    methods: [GET]
    requirements:
        url: .*/$
